# 开发环境配置模板
# 复制此文件为 application-dev-local.yml 并填入真实的配置信息
# application-dev-local.yml 不会被提交到 Git

spring:
  datasource:
    username: root
    password: your_database_password_here
  data:
    redis:
      password: your_redis_password_here

sky:
  datasource:
    username: root
    password: your_database_password_here
  redis:
    password: your_redis_password_here
  jwt:
    # 请生成强密钥，建议使用随机字符串生成器
    admin-secret-key: your_admin_jwt_secret_key_here
    user-secret-key: your_user_jwt_secret_key_here
  baidu:
    ak: your_baidu_map_ak_here

  # 微信支付相关配置
  wechat:
    appid: your_wechat_appid_here
    secret: your_wechat_secret_here
    mchid: your_merchant_id_here
    mchSerialNo: your_merchant_serial_no_here
    apiV3Key: your_api_v3_key_here
    notifyUrl: http://your_domain_here/notify/paySuccess
    refundNotifyUrl: http://your_domain_here/notify/refundSuccess

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: your_aliyun_access_key_id_here
    access-key-secret: your_aliyun_access_key_secret_here
    bucket-name: your_bucket_name_here

# 配置说明：
# 1. 复制此文件为 application-dev-local.yml
# 2. 将所有 "your_xxx_here" 替换为真实的配置值
# 3. application-dev-local.yml 已在 .gitignore 中排除，不会被提交