spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout
    username: root
    password: ${DB_PASSWORD:}
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      database : 2

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: takeout
    username: root
    password: ${DB_PASSWORD:}
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}
    database: 2
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${JWT_ADMIN_SECRET_KEY:}
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    # 设置jwt签名加密时使用的秘钥
    user-secret-key: ${JWT_USER_SECRET_KEY:}
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  shop:
    address: ${SHOP_ADDRESS:}
  baidu:
    ak: ${BAIDU_MAP_AK:}

  # 微信支付相关配置
  wechat:
    appid: ${WECHAT_APPID:}
    secret: ${WECHAT_SECRET:}
    mchid: 你的商户号
    mchSerialNo: 你的商户证书序列号
    privateKeyFilePath: classpath:cert/apiclient_key.pem
    apiV3Key: 你的APIv3密钥
    weChatPayCertFilePath: classpath:cert/wechatpay_cert.pem
    notifyUrl: http://41a12a0e.r8.cpolar.cn/notify/paySuccess
    refundNotifyUrl: http://41a12a0e.r8.cpolar.cn/notify/refundSuccess

# 阿里云OSS配置 - 开发环境
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    bucket-name: wakadori
