spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_db_password}
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:your_redis_password}
      database : 2

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: takeout
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:your_db_password}
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:your_redis_password}
    database: 2
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${JWT_ADMIN_SECRET:your_jwt_admin_secret}
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    # 设置jwt签名加密时使用的秘钥
    user-secret-key: ${JWT_USER_SECRET:your_jwt_user_secret}
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  shop:
    address : 江西省南昌市青云谱区墅溪公寓
  baidu:
    ak: ${BAIDU_AK:your_baidu_ak}

  # 微信支付相关配置
  wechat:
    appid: ${WECHAT_APPID:your_wechat_appid}
    secret: ${WECHAT_SECRET:your_wechat_secret}
    mchid: ${WECHAT_MCHID:your_merchant_id}
    mchSerialNo: ${WECHAT_MCH_SERIAL_NO:your_merchant_serial_no}
    privateKeyFilePath: classpath:cert/apiclient_key.pem
    apiV3Key: ${WECHAT_API_V3_KEY:your_api_v3_key}
    weChatPayCertFilePath: classpath:cert/wechatpay_cert.pem
    notifyUrl: ${WECHAT_NOTIFY_URL:http://localhost:8080/notify/paySuccess}
    refundNotifyUrl: ${WECHAT_REFUND_NOTIFY_URL:http://localhost:8080/notify/refundSuccess}

# 阿里云OSS配置 - 开发环境
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:https://oss-cn-beijing.aliyuncs.com}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:your_access_key_id}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:your_access_key_secret}
    bucket-name: ${ALIYUN_OSS_BUCKET:your_bucket_name}