spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout
    username: root
    password: 741963

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: takeout
    username: root
    password: 741963
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast@admin&123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
